<template>
   <div class="greetings">
    <div class="jumbotron">
  <h1 class="display-4"><h1 class="green"> 输入要预测的日期 (格式为“01-01”) </h1></h1>
  <p class="lead">Display the forecast data generated by the existing data and algorithm model.</p>
</div>
   </div>
  <div>
    <input type="text" id="date-input" v-model="inputDate" />
    <div v-if="selectedData">
      <p>{{ selectedData.date }} - {{ selectedData.value }}</p>
      <label for="range-selector">选择预测范围: </label>
      <select id="range-selector" v-model="selectedRange">
        <option value="1">1天</option>
        <option value="30">1月</option>
        <option value="365">1年</option>
      </select>
      <ul>
        <li v-for="data in rangeData">{{ data.date }} - {{ data.value }}</li>
      </ul>
    </div>
    <el-select v-model="value" :loading="loading" @click="updateOptions()">
	<el-option v-for="item in options" :key="item.id" :label="item.file" :value="item.id"></el-option>
</el-select>
  </div>
</template>

<script>
import jsonData from "../../output4.json";
import axios from "axios";

export default {
  name: "HelloWorld",
  data() {
    return {
      inputDate: "",
      selectedData: null,
      selectedRange: 1,
      options: [],
      list: [],//传回后端的参数
    };
  },
  methods:{
    //点击后更新下拉选项
    updateOptions(){
      this.list=[{value:''}, {value:''}];//按需修改
      axios.post('http://127.0.0.1:8000/api/getnewoption/', this.list).then(res=>{
        console.log(res);
        this.options=res.data;
      }).catch((mes)=>{
        this.$message.warning("请求失败")
      });},
  },
  computed: {
    rangeData() {
      if (!this.selectedData) return [];
      const { date} = this.selectedData;
      const dataIndex = jsonData.findIndex((d) => d.date === date);
      if (dataIndex === -1) return [];
      const endDataIndex = Math.min(
        dataIndex + Number(this.selectedRange),
        jsonData.length
      );
      return jsonData.slice(dataIndex, endDataIndex);
    },
  },
  watch: {
    inputDate(newDate) {
      this.selectedData = jsonData.find((d) => d.date === newDate);
    },
  },
};
</script>



